import React from 'react'
import styles from './SharedPage.module.css'

export default function Sustainability() {
  return (
    <div className={styles.page}>
      <h1 className={styles.title}>Clean clothes. Cleaner planet.</h1>
      <p className={styles.subtitle}>The garment care industry has a historically massive environmental footprint. Mysa is changing that.</p>

      <div className={styles.gridTwoCol}>
        <div className={styles.card}>
          <h3 className={styles.cardTitle}>100% PERC-Free</h3>
          <p className={styles.cardText}>Traditional dry cleaners use Perchloroethylene (PERC), a toxic chemical that pollutes groundwater and damages fabrics over time. We use exclusively non-toxic, advanced hydrocarbon solvents that are safe for you and the environment.</p>
        </div>

        <div className={styles.card}>
          <h3 className={styles.cardTitle}>Water Conservation</h3>
          <p className={styles.cardText}>Our High-Efficiency (HE) commercial washing machines use 40% less water than traditional commercial washers. We capture, filter, and reuse water wherever safely possible, saving millions of liters annually.</p>
        </div>

        <div className={styles.card}>
          <h3 className={styles.cardTitle}>Zero Plastic Packaging</h3>
          <p className={styles.cardText}>Say goodbye to single-use plastic garment bags. All Mysa orders are returned in reusable, breathable fabric garment covers. We also exclusively use sustainable wooden hangers that you can return to us for recycling.</p>
        </div>

        <div className={styles.card}>
          <h3 className={styles.cardTitle}>Carbon Neutral Fleet</h3>
          <p className={styles.cardText}>Our valet service operates on optimized routing algorithms to reduce driving time. Furthermore, we offset 100% of the carbon emissions generated by our delivery fleet through certified environmental protection projects.</p>
        </div>
      </div>
    </div>
  )
}
